name: Lab-Workflow
on:
  push:
    branches:
      - main
env: 
  WORDING: "PIMSIRI"

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: check github environment
        run: hostname

      - name: create variable
        run: echo "BUILD_ARGS=prod-1.0.0" >> $GITHUB_ENV

      - name: build application
        run: echo "Hello ${{ env.WORDING }} by $BUILD_ARGS"
  deploy: 
    runs-on: manow
    steps:
      - name: check github environment
        run: hostname