name: pimsiri-flow
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: manow
    steps:
      - name: check server-info
        run: lsb_release -a
      - name: show list
        run: ls -la
      - name: display wording
        run: echo hello ${{ github.actor }}