name: pimsiri-flow
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
    inputs: 
      version: 
       discription: "inputs version"
       required: true 
jobs:
  build:
    runs-on: Manow
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: docker login
        run: docker login -u manowpsr -p ${{ Secrets.DOCKER_PASS }}

      - name: build and push
        run: |
          cd app
          docker build -t manowpsr/manow:${{ github.event.inputs.version }} .
          docker push manowpsr/manow:${{ github.event.inputs.version }}

  Deploy: 
    needs: build 
    runs-on: manow
    steps: 
      - name: Minikube start 
        run: minikube start
      - name: create deploy 
        run: | 
          kubectl create namespace manow-ns
          kubectl apply -f pod.yaml
          